language: node_js
node_js:
  - 11.1.0
cache: npm
install:
  - npm install --global lerna jest now
  - lerna bootstrap
script:
  - lerna run test
  - lerna run build
deploy:
  provider: script
  script: bash -x scripts/deploy.sh
  skip_cleanup: true
  on:
    all_branches: true
env:
  global:
    secure: "c2KMg3rgdixnsrx4afFM8sQ/lBrp+jIe0cc8AUWIu0jxBmdMKhBrPlmZ7VG0xeGvNlzocV1i9By1dqGz2pGTiy9ws7QTreFo9WsOPsm+AWSQHuUM5Rl7Yf264sMLi0dIKTHD8f45dyjhJYDm5PqmZl+4AwUWXfAfYu9U0ArW00vMMXRKlC8mPdgHKWgCh/hwh7fRd2QtWEvEq+JocYc+csq/n35qP89knR5T+t/waLlMsPg1bBKQMMlNfIr7n7QWldFpDlAWNV+eo8mJcthdqo+UBEs+0bDlvF5V94MDcyQQK6zdNwKOOH42nbfH+CPNfS34vYSEIZc3K0n/fkHWka0QuOPJq6SGSHF0o2dPFgZB0yxptOGTNzMUaKieQiGGhgwTBwAEmeKCiCQMpsXETcQtv62erMA8qjy9TgakGfm2onQ/RYU2nNWsFIQcFrVIoEC8fbp3qQrl7DOEz8eM0ZIY7BWEKnof/dvLB2/6r99pc7t2MTEDgxAx5sKtuw+NqLK02Kko9UKB7Ju2aQdQ85WKYRn/S1pyM3QRvviW+0EldUmOFJHWPV6D/aRm1hCh1h3G9MDJZFkkVDU9Xm+6U/9xfG81jhCdXKRQCtSe1oxKchr5+kwbth8mFu9mdSpT6yBOWPmYRrt30iFdM7Au399eU4kWs/23ZCua9MWR+s8="
