language: node_js
node_js:
  - "11.1.0"

cache: npm

install:
  - npm install --global lerna jest now
  - lerna bootstrap

script:
  - lerna run test
  - lerna run build

deploy:
  provider: script
  script: bash -x scripts/deploy.sh
  skip_cleanup: true
  on:
    all_branches: true

env:
  global:
    secure: kWuXfRyfMaGmaNTqJA2wGyu4xnv9prjxVGem/0vc1G4X+VJNdcQRArLOZ10/wJ5GjdRDNZEoRJzUaZ34Tx+15F/EI1jfCNHz8txwwrlysVpT1SNPqHkGhell6HWjfVgOAp5Ebds7A/7TXbtQfVIG9RLeSA+4ZM5/gLmdSamABzyQBuD0XEfaHdLoh2mLXEMCVrpZrZxo0cadb+6nqduEpFV4WCw9wq53sMq+hRlP5mb0N0POVhGs7C8U2ih+QXcTICwJi+qp8UOfkevZhNs41Nw2j2H2AK2zkWjTLE8s4lNMiRCFSbf8KJXMcxQCMFWJQsYocDzHmBbe4E4Ql54ubZU7PwOcyzgRC6IArVv4LRvXoTJT5TEluGzN8Gehhsf1x5AgdE4t9nsTs7ehoDbMS7w8pWdl1Dmjbg0cK5SjMFmL77ZXM83y2NfpXbGhDLQxX4WBp2143fZr0uUT79gM1LeSBypYmAfo6RicV5/u7dUrlpJHA0Nlf9c4xGUo5UCSsleItlv5ZPA0R+mZxPfsWensfdDrqpsiKD3A+LicrBGapQWn4KRUntXJVBBMn1/rSey27mJXs9kr9PvPxrlyb7aYvIJ2ju7i0YnYqplPQ27zaiwZu0U6mtsV7jTtyBrEPPHF3U7DIewfRo8uPwoSoTuQPD5jWuTEipkCfOgVgV8=
