language: node_js
node_js:
- 11.1.0
cache: npm
install:
- npm install --global lerna jest now
- lerna bootstrap
script:
- lerna run test
- lerna run build
deploy:
  provider: script
  script: bash -x scripts/deploy.sh
  skip_cleanup: true
  on:
    all_branches: true
env:
  global:
    secure: niyHMnjJzGZxF4yM1BuTxedxSc88IIIq5oedpz7Q44L9E0G5OIGqAnPppstpxUIY4M0jA8PJJvmQ3Lk6zXSbbA/lZkO4XpEZXqCmYcmMQPxQjzoUkO0+jKXhsNaDzAPZjx+nsAUqrc5IPRG1SnDe1NllND9KglxWGNiikC4TrYlxEBpo3XcYPxbBsLU6FlH98qh+Yl8d/9AGxBe/g4vSk5gMi/kDJA8Em5oMS3yRvVn4XIaP6GnV0Er4JKMfpnRL131DpJhPbJolpzBdBlR2juWvdtBNuqYOqF+jKgqduwuoCpVhbyfs5e5whJ6EOHFK92wo1Q/Gbj7osNETLxgvD8pqPwZ0pPdkwN7WVeEipTCWdyXIm+CDIeNMZiWs0G51mUIH+7Zqa+AH5aIKf2ODNYAuJmpFqEnBfObBLZUGv5OX7taL4G8dkq7lWvE8HaezyK/mlpbicuxZdfR/twBFJ4va7Wp48CMi7OaFbGIlUwLqoMUdainQfPeAx8kWbZuztmPcrpxQ+Ne3N6eMPWgh8MwcQZtU6LfXMMncUboEpegFSmNe9spyGNQrSUNgsGtViV0QNeIhaWXTlzMErSx7dSKcyhMypMbC77R2ZQSTU3Xpw5k1PSAErHbFio12061u4ox1AmL960cTnBuLbcdGOH3GBgx/MZJL7sseOFqZobM=
    secure: ja4B2198cffmE2h6JUCfLOImWOLkFnRzPIvLav17FCdW1xLAkgfB8jmPzigjRTwriTciGF55qYix0fpns19MCReSqlzNHCENEuWJZ2M2YspfvnJo9d00myhAeHKYqG+T7M4LmHtIPJbO2n/kYYqRV3i5NjjQEFcCRxdW240gIz4iS6zt3/EcG8fylXUMSp+bYLaK2uC4YlIS29bIC88B3u8Ypkn+7b9enTzSq7B/xrJOI+3dfS7izZOvLEVTIt7r1/nrRVPgG/BBdOwdi9wq5i60FTyDyr4LVMa9pXo2m8BFCFGOFuAPFrJqzvXIcj/8C57CjzJfW7Ulv6pAzohtG06htSEV15uJf4rNP6tYjzO1o7Tt6iw+VbX24/YY1Q7Wd/tyua9FrjjtalMhNxwbqRjxwhhcLOA7zdXdVVs5yDSEnPAh5nlvthMRhcZUkiS/FaT1Imik+vlRrC7XGPq/SmGPS5fCFnZa2YfRV8vEZtsThuIaHbQGMXDYb4q1O/bi4Av56zEo6bVDQQZkS4UXQu8673P9yBu8/s8K/go/Lp2dH4AeYGx0fGubBzU4fupNvJTVoSDTESUy58aTePZ+elgqespc2rGWHfZtSnXotKVBovkXXtS2FpbWzJYhKF31NsPAIIVApYW7A1Gi8znkbpYK90XNZwfo+CMZsQd+WqQ=