language: node_js
node_js:
  - "11.1.0"

cache: npm

install:
  - npm install --global lerna jest
  - lerna bootstrap

matrix:
  include:
    - name: "Api pipeline"
      env: PACKAGE_LOCATION=packages/api PACKAGE_NAME=nolli-api
    - name: "Web pipeline"
      env: PACKAGE_LOCATION=packages/web PACKAGE_NAME=nolli-web

script:
  - cd $PACKAGE_LOCATION
  - npm test
  - npm run-script build
  - cd -

deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip_cleanup: true
  app: $PACKAGE_NAME
  on:
    all_branches: true
